import {PrismaClient} from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
    await prisma.account.upsert({
        where: {
            email: 'hello@kyawzinthiha.com'
        },
        update: {},
        create: {
            email: 'hello@kyawzinthiha.com',
            username: 'kyawzinthiha',
            password: '123456',
            user: {
                create: {
                    name: 'Kyaw Zin Thiha',
                    title: 'Autogenerated Title',
                    subtitle: 'Autogenerated Subtitle',
                    bio: 'Autogenerated Bio',
                    avatar: ''
                }
            }
        }
    });
}

main();