import { PrismaClient } from '@prisma/client';
import { BcryptService } from '../src/helper/bcrypt.service';

const prisma = new PrismaClient();
const bcrypt = new BcryptService();

async function main() {
	await prisma.account.upsert({
		where: {
			email: 'hello@kyawzinthiha.com',
		},
		update: {},
		create: {
			email: 'hello@kyawzinthiha.com',
			username: 'kyawzinthiha',
			password: bcrypt.hash('kyawzinthiha'),
			user: {
				create: {
					name: 'Kyaw Zin Thiha',
					title: 'Autogenerated Title',
					subtitle: 'Autogenerated Subtitle',
					bio: 'Autogenerated Bio',
					avatar: '',
				},
			},
		},
	});
}

main()
	.then(async () => {
		await prisma.$disconnect();
	})
	.catch(async (e) => {
		console.error(e);
		await prisma.$disconnect();
		process.exit(1);
	});